# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
#relative_permalinks: true

# Setup
title:               Valar Morghulis
tagline:             'Jiadong Dan'
description:         'Valar Morghulis'
#url:                 http://jiadong.co
baseurl:             ''
paginate:            15

# About/contact
author:
  name:              Jiadong Dan
  url:               https://jiadong.co
  email:             jiadong.dan@u.nus.edu

# Custom vars
version:             1.0.0
